name: Test

on:
  pull_request:
    paths-ignore:
      - '**.md'    
  push:    
    branches:
      - master
    paths-ignore:
      - '**.md'
jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest , ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: yarn --frozen-lockfile
      - run: yarn codegen
      - run: yarn test
      - run: (cd examples/pure && yarn install --force && yarn test)
      - run: (cd examples && yarn install && yarn test)

  # test_windows:
  #   runs-on: windows-latest      
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: true
  #     - name: Setup node 12
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 12.x
  #     - run: yarn --frozen-lockfile
  #     - run: yarn codegen
  #     - run: yarn test
  #     - run: (cd examples/pure && yarn install --force && yarn test)
  #     - run: (cd examples && yarn install && yarn test)
        