name: Test

on:
  pull_request:
    paths-ignore:
      - '**.md'    
  push:    
    branches:
      - master
    paths-ignore:
      - '**.md'
jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
            - os: windows-latest
              shell: msys2
            - os: ubuntu-latest
              shell: bash
            - os: macos-latest
              shell: bash
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Setup msys
        runs-on: windows-latest
        uses: msys2/setup-msys2@v2
      - run: yarn --frozen-lockfile
      - run: yarn codegen
      - run: yarn test
      - run: (cd examples/pure && yarn install --force && yarn test)
      - run: (cd examples && yarn install && yarn test)